### ISSUE TITLE
Talk description

### ISSUE THREAD

**Issue by nikgraf** [geraldb/talks#1]
Hey Gerald, I tried to reach you for a talk description on your Gatsby talk. Let's try it here

Do you have time next Wednesday 13th July? I would need a 2-3 sentence description 😄

**Comment by geraldb** [comment]
@nikgraf  Sorry I was offline yesterday. As sent by email. Here's the suggestion (edit/change as you please):

Stay Static - Build Single-Page Static (Web)Sites with the Great Gatsby

Learn more about the Great Gatsby [1] - a new static (web)site build package
 with 3000+ stars (on GitHub) that lets you build your
next blog or project (web)site using Webpack, React (+ React Router)
and Markdown.

Let's look at the Stay Static [2] showcase sample to see how can add
pages, posts or datafiles to your site and how Gatsby compares
to alternative offerings (with React e.g. Phenomic, Leo etc. or
without e.g. Jekyll & Hyde).
Or why not (continue to) build your very own static site builder?

[1] https://github.com/gatsbyjs/gatsby
[2] http://staystatic.github.io

 Und vielleicht ein kleines Bio dazu:

Gerald Bauer studied at the Wirtschaftsuniversität Wien and has worked
for Google, Apple, and others overseas and now lives in the Wagram
hills in the Weinviertel and is an enthusiastic collector of football
and beer data. Skills include Ruby, SQLite and HTML.

  Danke für die Organization. Freue mich. Gruss.
