### ISSUE TITLE
question: software advice for markdown presentations

### ISSUE THREAD

**Issue by epogrebnyak** [geraldb/talks#3]
Many thanks for sharing a very impressive list of presentations in your repo!

I was wondering if you use any specific software (eg as in https://gist.github.com/johnloy/27dd124ad40e210e91c70dd1c24ac8c8) to show these presentations, or do you keep these files as notes for reference?

**Comment by geraldb** [comment]
Sorry to disappoint I use my own little self-made markdown to presentation package / tool, see <http://slideshow-s9.github.io/> and you can find some template pack(ages) @ <http://slideshow-templates.github.io/>.  Cheers. Prost. 

Lately I have only used the "raw" markdown page from github itself - it's really a matter of taste. The idea is that if you use the page here - your audience can lookup the notes easier - they are looking at the notes right now - if you use some slides usually you know how human nature is they do not care once the show is over to lookup anything.  Anyways, all the best. Cheers. Prost.
